title: Edison Docs
baseurl: /rix-docs

###### Jekyll ######

source: src
permalink: pretty

sass:
  sass_dir: _sass
  cache: false
  style: compressed

defaults:
  - scope:
      path: ''
    values:
      layout: 'default'
